// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "events" (
  "seq" INTEGER NOT NULL,
  "args" TEXT NOT NULL,
  "op" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "session" TEXT,
  "ts" TEXT NOT NULL,
  PRIMARY KEY ("seq")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "tasks" (
  "scope" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "created_seq" INTEGER NOT NULL,
  "pos" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "text" TEXT NOT NULL,
  "updated_seq" INTEGER NOT NULL,
  PRIMARY KEY ("scope", "id")
)`,
		`CREATE TABLE IF NOT EXISTS "task_deps" (
  "scope" TEXT NOT NULL,
  "task_id" TEXT NOT NULL,
  "depends_on" TEXT NOT NULL,
  "created_seq" INTEGER NOT NULL,
  PRIMARY KEY ("scope", "task_id", "depends_on")
)`,
	}
}
