// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "memories" (
  "id" INTEGER NOT NULL,
  "access_count" INTEGER NOT NULL,
  "content" TEXT NOT NULL,
  "content_sha256" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "importance" REAL NOT NULL,
  "kind" TEXT NOT NULL,
  "last_accessed_at" TEXT,
  "last_consolidated_at" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "scope_label" TEXT NOT NULL,
  "source" TEXT,
  "strength" REAL NOT NULL,
  "superseded_by" INTEGER,
  PRIMARY KEY ("id")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "trigrams" (
  "memory_id" INTEGER NOT NULL,
  "gram" TEXT NOT NULL,
  PRIMARY KEY ("memory_id", "gram")
)`,
	}
}
