// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Event struct {
	Seq     int64   `db:"seq"`
	Args    string  `db:"args"`
	Op      string  `db:"op"`
	Scope   string  `db:"scope"`
	Session *string `db:"session"`
	Ts      string  `db:"ts"`
}

type EventDomain interface {
	GetEvent(ctx context.Context, seq int64) *lazy.Lazy[Event]
	GetEventBatch(ctx context.Context, keys []int64) *lazy.Lazy[Event]
	InsertEvent(ctx context.Context, row Event) (*Event, error)
	DeleteEvent(ctx context.Context, seq int64) (*Event, error)
	UpdateEvent(ctx context.Context, row Event) (*Event, error)
}

type eventDomain struct{}

func NewEventDomain() *eventDomain {
	return &eventDomain{}
}

func ScanEvent(row lazy.ScanRow) (Event, error) {
	var out Event
	err := row.Scan(
		&out.Seq,
		&out.Args,
		&out.Op,
		&out.Scope,
		&out.Session,
		&out.Ts,
	)
	return out, err
}

func (d *eventDomain) one(rows *sql.Rows) (*Event, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanEvent(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *eventDomain) GetEvent(ctx context.Context, seq int64) *lazy.Lazy[Event] {
	l := lazy.New(ScanEvent)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "seq", "args", "op", "scope", "session", "ts" FROM "events" WHERE "seq" = $1`,
		seq,
	)
	out, err := ScanEvent(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *eventDomain) GetEventBatch(ctx context.Context, keys []int64) *lazy.Lazy[Event] {
	l := lazy.New(ScanEvent)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "seq", "args", "op", "scope", "session", "ts" FROM "events" WHERE "seq" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Event
	for rows.Next() {
		row, err := ScanEvent(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *eventDomain) InsertEvent(ctx context.Context, row Event) (*Event, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "events" ("seq", "args", "op", "scope", "session", "ts") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "seq", "args", "op", "scope", "session", "ts"`,
		row.Seq,
		row.Args,
		row.Op,
		row.Scope,
		row.Session,
		row.Ts,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *eventDomain) DeleteEvent(ctx context.Context, seq int64) (*Event, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "events" WHERE "seq" = $1 RETURNING "seq", "args", "op", "scope", "session", "ts"`,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *eventDomain) UpdateEvent(ctx context.Context, row Event) (*Event, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "events" SET "args" = $1, "op" = $2, "scope" = $3, "session" = $4, "ts" = $5 WHERE "seq" = $6 RETURNING "seq", "args", "op", "scope", "session", "ts"`,
		row.Args,
		row.Op,
		row.Scope,
		row.Session,
		row.Ts,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
