// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Meta struct {
	Key   string `db:"key"`
	Value string `db:"value"`
}

type MetaDomain interface {
	GetMeta(ctx context.Context, key string) *lazy.Lazy[Meta]
	GetMetaBatch(ctx context.Context, keys []string) *lazy.Lazy[Meta]
	InsertMeta(ctx context.Context, row Meta) (*Meta, error)
	DeleteMeta(ctx context.Context, key string) (*Meta, error)
	UpdateMeta(ctx context.Context, row Meta) (*Meta, error)
}

type metaDomain struct{}

func NewMetaDomain() *metaDomain {
	return &metaDomain{}
}

func ScanMeta(row lazy.ScanRow) (Meta, error) {
	var out Meta
	err := row.Scan(
		&out.Key,
		&out.Value,
	)
	return out, err
}

func (d *metaDomain) one(rows *sql.Rows) (*Meta, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanMeta(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *metaDomain) GetMeta(ctx context.Context, key string) *lazy.Lazy[Meta] {
	l := lazy.New(ScanMeta)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "key", "value" FROM "meta" WHERE "key" = $1`,
		key,
	)
	out, err := ScanMeta(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *metaDomain) GetMetaBatch(ctx context.Context, keys []string) *lazy.Lazy[Meta] {
	l := lazy.New(ScanMeta)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "key", "value" FROM "meta" WHERE "key" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Meta
	for rows.Next() {
		row, err := ScanMeta(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *metaDomain) InsertMeta(ctx context.Context, row Meta) (*Meta, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "meta" ("key", "value") VALUES ($1, $2) RETURNING "key", "value"`,
		row.Key,
		row.Value,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *metaDomain) DeleteMeta(ctx context.Context, key string) (*Meta, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "meta" WHERE "key" = $1 RETURNING "key", "value"`,
		key,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *metaDomain) UpdateMeta(ctx context.Context, row Meta) (*Meta, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "meta" SET "value" = $1 WHERE "key" = $2 RETURNING "key", "value"`,
		row.Value,
		row.Key,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
