// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type TaskDep struct {
	Scope      string `db:"scope"`
	TaskId     string `db:"task_id"`
	Kind       string `db:"kind"`
	CreatedSeq int64  `db:"created_seq"`
	DependsOn  string `db:"depends_on"`
}

type TaskDepDomain interface {
	GetTaskDep(ctx context.Context, scope string, taskId string, kind string) *lazy.Lazy[TaskDep]
	WindowTaskDepByScopeTaskId(ctx context.Context, scope string, taskId string, from string, to string, limit int32) *lazy.Lazy[TaskDep]
	PageTaskDepByScopeTaskId(ctx context.Context, scope string, taskId string, after string, limit int32) *lazy.Lazy[TaskDep]
	InsertTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error)
	DeleteTaskDep(ctx context.Context, scope string, taskId string, kind string) (*TaskDep, error)
	UpdateTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error)
}

type taskDepDomain struct{}

func NewTaskDepDomain() *taskDepDomain {
	return &taskDepDomain{}
}

func ScanTaskDep(row lazy.ScanRow) (TaskDep, error) {
	var out TaskDep
	err := row.Scan(
		&out.Scope,
		&out.TaskId,
		&out.Kind,
		&out.CreatedSeq,
		&out.DependsOn,
	)
	return out, err
}

func (d *taskDepDomain) one(rows *sql.Rows) (*TaskDep, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTaskDep(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *taskDepDomain) GetTaskDep(ctx context.Context, scope string, taskId string, kind string) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "scope", "task_id", "kind", "created_seq", "depends_on" FROM "task_deps" WHERE "scope" = $1 AND "task_id" = $2 AND "kind" = $3`,
		scope,
		taskId,
		kind,
	)
	out, err := ScanTaskDep(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *taskDepDomain) WindowTaskDepByScopeTaskId(ctx context.Context, scope string, taskId string, from string, to string, limit int32) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "scope", "task_id", "kind", "created_seq", "depends_on" FROM "task_deps" WHERE "scope" = $1 AND "task_id" = $2 AND "kind" >= $3 AND "kind" < $4 ORDER BY "scope", "task_id", "kind" LIMIT $5`,
		scope,
		taskId,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []TaskDep
	for rows.Next() {
		row, err := ScanTaskDep(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDepDomain) PageTaskDepByScopeTaskId(ctx context.Context, scope string, taskId string, after string, limit int32) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "scope", "task_id", "kind", "created_seq", "depends_on" FROM "task_deps" WHERE "scope" = $1 AND "task_id" = $2 AND "kind" > $3 ORDER BY "scope", "task_id", "kind" LIMIT $4`,
		scope,
		taskId,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []TaskDep
	for rows.Next() {
		row, err := ScanTaskDep(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDepDomain) InsertTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "task_deps" ("scope", "task_id", "kind", "created_seq", "depends_on") VALUES ($1, $2, $3, $4, $5) RETURNING "scope", "task_id", "kind", "created_seq", "depends_on"`,
		row.Scope,
		row.TaskId,
		row.Kind,
		row.CreatedSeq,
		row.DependsOn,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDepDomain) DeleteTaskDep(ctx context.Context, scope string, taskId string, kind string) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "task_deps" WHERE "scope" = $1 AND "task_id" = $2 AND "kind" = $3 RETURNING "scope", "task_id", "kind", "created_seq", "depends_on"`,
		scope,
		taskId,
		kind,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDepDomain) UpdateTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "task_deps" SET "created_seq" = $1, "depends_on" = $2 WHERE "scope" = $3 AND "task_id" = $4 AND "kind" = $5 RETURNING "scope", "task_id", "kind", "created_seq", "depends_on"`,
		row.CreatedSeq,
		row.DependsOn,
		row.Scope,
		row.TaskId,
		row.Kind,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
