// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Task struct {
	Scope      string `db:"scope"`
	Id         string `db:"id"`
	CreatedSeq int64  `db:"created_seq"`
	Pos        int64  `db:"pos"`
	Status     string `db:"status"`
	Text       string `db:"text"`
	UpdatedSeq int64  `db:"updated_seq"`
}

type TaskDomain interface {
	GetTask(ctx context.Context, scope string, id string) *lazy.Lazy[Task]
	WindowTaskByScope(ctx context.Context, scope string, from string, to string, limit int32) *lazy.Lazy[Task]
	PageTaskByScope(ctx context.Context, scope string, after string, limit int32) *lazy.Lazy[Task]
	InsertTask(ctx context.Context, row Task) (*Task, error)
	DeleteTask(ctx context.Context, scope string, id string) (*Task, error)
	UpdateTask(ctx context.Context, row Task) (*Task, error)
}

type taskDomain struct{}

func NewTaskDomain() *taskDomain {
	return &taskDomain{}
}

func ScanTask(row lazy.ScanRow) (Task, error) {
	var out Task
	err := row.Scan(
		&out.Scope,
		&out.Id,
		&out.CreatedSeq,
		&out.Pos,
		&out.Status,
		&out.Text,
		&out.UpdatedSeq,
	)
	return out, err
}

func (d *taskDomain) one(rows *sql.Rows) (*Task, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTask(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *taskDomain) GetTask(ctx context.Context, scope string, id string) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "scope", "id", "created_seq", "pos", "status", "text", "updated_seq" FROM "tasks" WHERE "scope" = $1 AND "id" = $2`,
		scope,
		id,
	)
	out, err := ScanTask(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *taskDomain) WindowTaskByScope(ctx context.Context, scope string, from string, to string, limit int32) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "scope", "id", "created_seq", "pos", "status", "text", "updated_seq" FROM "tasks" WHERE "scope" = $1 AND "id" >= $2 AND "id" < $3 ORDER BY "scope", "id" LIMIT $4`,
		scope,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Task
	for rows.Next() {
		row, err := ScanTask(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDomain) PageTaskByScope(ctx context.Context, scope string, after string, limit int32) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "scope", "id", "created_seq", "pos", "status", "text", "updated_seq" FROM "tasks" WHERE "scope" = $1 AND "id" > $2 ORDER BY "scope", "id" LIMIT $3`,
		scope,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Task
	for rows.Next() {
		row, err := ScanTask(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDomain) InsertTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "tasks" ("scope", "id", "created_seq", "pos", "status", "text", "updated_seq") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "scope", "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		row.Scope,
		row.Id,
		row.CreatedSeq,
		row.Pos,
		row.Status,
		row.Text,
		row.UpdatedSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) DeleteTask(ctx context.Context, scope string, id string) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "tasks" WHERE "scope" = $1 AND "id" = $2 RETURNING "scope", "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		scope,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) UpdateTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "tasks" SET "created_seq" = $1, "pos" = $2, "status" = $3, "text" = $4, "updated_seq" = $5 WHERE "scope" = $6 AND "id" = $7 RETURNING "scope", "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		row.CreatedSeq,
		row.Pos,
		row.Status,
		row.Text,
		row.UpdatedSeq,
		row.Scope,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
