// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Task struct {
	Id         string `db:"id"`
	CreatedSeq int64  `db:"created_seq"`
	Pos        int64  `db:"pos"`
	Status     string `db:"status"`
	Text       string `db:"text"`
	UpdatedSeq int64  `db:"updated_seq"`
}

type TaskDomain interface {
	GetTask(ctx context.Context, id string) *lazy.Lazy[Task]
	GetTaskBatch(ctx context.Context, keys []string) *lazy.Lazy[Task]
	InsertTask(ctx context.Context, row Task) (*Task, error)
	DeleteTask(ctx context.Context, id string) (*Task, error)
	UpdateTask(ctx context.Context, row Task) (*Task, error)
}

type taskDomain struct{}

func NewTaskDomain() *taskDomain {
	return &taskDomain{}
}

func ScanTask(row lazy.ScanRow) (Task, error) {
	var out Task
	err := row.Scan(
		&out.Id,
		&out.CreatedSeq,
		&out.Pos,
		&out.Status,
		&out.Text,
		&out.UpdatedSeq,
	)
	return out, err
}

func (d *taskDomain) one(rows *sql.Rows) (*Task, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTask(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *taskDomain) GetTask(ctx context.Context, id string) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "created_seq", "pos", "status", "text", "updated_seq" FROM "tasks" WHERE "id" = $1`,
		id,
	)
	out, err := ScanTask(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *taskDomain) GetTaskBatch(ctx context.Context, keys []string) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "created_seq", "pos", "status", "text", "updated_seq" FROM "tasks" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Task
	for rows.Next() {
		row, err := ScanTask(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDomain) InsertTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "tasks" ("id", "created_seq", "pos", "status", "text", "updated_seq") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		row.Id,
		row.CreatedSeq,
		row.Pos,
		row.Status,
		row.Text,
		row.UpdatedSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) DeleteTask(ctx context.Context, id string) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "tasks" WHERE "id" = $1 RETURNING "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) UpdateTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "tasks" SET "created_seq" = $1, "pos" = $2, "status" = $3, "text" = $4, "updated_seq" = $5 WHERE "id" = $6 RETURNING "id", "created_seq", "pos", "status", "text", "updated_seq"`,
		row.CreatedSeq,
		row.Pos,
		row.Status,
		row.Text,
		row.UpdatedSeq,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
