// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type TaskDep struct {
	TaskId     string `db:"task_id"`
	DependsOn  string `db:"depends_on"`
	CreatedSeq int64  `db:"created_seq"`
}

type TaskDepDomain interface {
	GetTaskDep(ctx context.Context, taskId string, dependsOn string) *lazy.Lazy[TaskDep]
	WindowTaskDepByTaskId(ctx context.Context, taskId string, from string, to string, limit int32) *lazy.Lazy[TaskDep]
	PageTaskDepByTaskId(ctx context.Context, taskId string, after string, limit int32) *lazy.Lazy[TaskDep]
	InsertTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error)
	DeleteTaskDep(ctx context.Context, taskId string, dependsOn string) (*TaskDep, error)
	UpdateTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error)
}

type taskDepDomain struct{}

func NewTaskDepDomain() *taskDepDomain {
	return &taskDepDomain{}
}

func ScanTaskDep(row lazy.ScanRow) (TaskDep, error) {
	var out TaskDep
	err := row.Scan(
		&out.TaskId,
		&out.DependsOn,
		&out.CreatedSeq,
	)
	return out, err
}

func (d *taskDepDomain) one(rows *sql.Rows) (*TaskDep, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTaskDep(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *taskDepDomain) GetTaskDep(ctx context.Context, taskId string, dependsOn string) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "task_id", "depends_on", "created_seq" FROM "task_deps" WHERE "task_id" = $1 AND "depends_on" = $2`,
		taskId,
		dependsOn,
	)
	out, err := ScanTaskDep(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *taskDepDomain) WindowTaskDepByTaskId(ctx context.Context, taskId string, from string, to string, limit int32) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "task_id", "depends_on", "created_seq" FROM "task_deps" WHERE "task_id" = $1 AND "depends_on" >= $2 AND "depends_on" < $3 ORDER BY "task_id", "depends_on" LIMIT $4`,
		taskId,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []TaskDep
	for rows.Next() {
		row, err := ScanTaskDep(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDepDomain) PageTaskDepByTaskId(ctx context.Context, taskId string, after string, limit int32) *lazy.Lazy[TaskDep] {
	l := lazy.New(ScanTaskDep)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "task_id", "depends_on", "created_seq" FROM "task_deps" WHERE "task_id" = $1 AND "depends_on" > $2 ORDER BY "task_id", "depends_on" LIMIT $3`,
		taskId,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []TaskDep
	for rows.Next() {
		row, err := ScanTaskDep(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDepDomain) InsertTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "task_deps" ("task_id", "depends_on", "created_seq") VALUES ($1, $2, $3) RETURNING "task_id", "depends_on", "created_seq"`,
		row.TaskId,
		row.DependsOn,
		row.CreatedSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDepDomain) DeleteTaskDep(ctx context.Context, taskId string, dependsOn string) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "task_deps" WHERE "task_id" = $1 AND "depends_on" = $2 RETURNING "task_id", "depends_on", "created_seq"`,
		taskId,
		dependsOn,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDepDomain) UpdateTaskDep(ctx context.Context, row TaskDep) (*TaskDep, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "task_deps" SET "created_seq" = $1 WHERE "task_id" = $2 AND "depends_on" = $3 RETURNING "task_id", "depends_on", "created_seq"`,
		row.CreatedSeq,
		row.TaskId,
		row.DependsOn,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
