// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "decisions" (
  "id" INTEGER NOT NULL,
  "answer" TEXT NOT NULL,
  "confidence" REAL,
  "decider" TEXT NOT NULL,
  "outcome" TEXT,
  "question" TEXT NOT NULL,
  "reviewer" TEXT,
  "reviewer_answer" TEXT,
  "scope" TEXT NOT NULL,
  "session" TEXT,
  "site" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "ts" TEXT NOT NULL,
  "unsure" INTEGER NOT NULL,
  PRIMARY KEY ("id")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "trainings" (
  "id" INTEGER NOT NULL,
  "candidate" TEXT NOT NULL,
  "checkpoint" TEXT NOT NULL,
  "constant" TEXT NOT NULL,
  "held_rows" INTEGER NOT NULL,
  "incumbent" TEXT,
  "promoted" INTEGER NOT NULL,
  "rows" INTEGER NOT NULL,
  "run_dir" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "skipped" INTEGER NOT NULL,
  "train_rows" INTEGER NOT NULL,
  "trainer" TEXT NOT NULL,
  "ts" TEXT NOT NULL,
  PRIMARY KEY ("id")
)`,
	}
}
