// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "faults" (
  "seq" INTEGER NOT NULL,
  "at" TIMESTAMP NOT NULL,
  "message" TEXT NOT NULL,
  "session_id" TEXT NOT NULL,
  PRIMARY KEY ("seq")
)`,
		`CREATE TABLE IF NOT EXISTS "files" (
  "session_id" TEXT NOT NULL,
  "path" TEXT NOT NULL,
  "hash" TEXT NOT NULL,
  "mtime" INTEGER NOT NULL,
  PRIMARY KEY ("session_id", "path")
)`,
		`CREATE TABLE IF NOT EXISTS "messages" (
  "seq" INTEGER NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "reasoning" TEXT,
  "role" TEXT NOT NULL,
  "session_id" TEXT NOT NULL,
  "tool_id" TEXT,
  PRIMARY KEY ("seq")
)`,
		`CREATE TABLE IF NOT EXISTS "sessions" (
  "id" TEXT NOT NULL,
  "cwd" TEXT NOT NULL,
  "ended_at" TIMESTAMP,
  "exit" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "started_at" TIMESTAMP NOT NULL,
  "version" TEXT NOT NULL,
  PRIMARY KEY ("id")
)`,
		`CREATE TABLE IF NOT EXISTS "tool_calls" (
  "id" TEXT NOT NULL,
  "args" TEXT NOT NULL,
  "ended_at" TIMESTAMP,
  "err" TEXT,
  "message_seq" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "result" TEXT,
  "started_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
)`,
		`CREATE TABLE IF NOT EXISTS "usage" (
  "message_seq" INTEGER NOT NULL,
  "cache_read" INTEGER NOT NULL,
  "cache_write" INTEGER NOT NULL,
  "completion" INTEGER NOT NULL,
  "prompt" INTEGER NOT NULL,
  PRIMARY KEY ("message_seq")
)`,
	}
}
