// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"
	"time"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Fault struct {
	Seq       int64     `db:"seq"`
	At        time.Time `db:"at"`
	Message   string    `db:"message"`
	SessionId string    `db:"session_id"`
}

type FaultDomain interface {
	GetFault(ctx context.Context, seq int64) *lazy.Lazy[Fault]
	GetFaultBatch(ctx context.Context, keys []int64) *lazy.Lazy[Fault]
	InsertFault(ctx context.Context, row Fault) (*Fault, error)
	DeleteFault(ctx context.Context, seq int64) (*Fault, error)
	UpdateFault(ctx context.Context, row Fault) (*Fault, error)
}

type faultDomain struct{}

func NewFaultDomain() *faultDomain {
	return &faultDomain{}
}

func ScanFault(row lazy.ScanRow) (Fault, error) {
	var out Fault
	err := row.Scan(
		&out.Seq,
		&out.At,
		&out.Message,
		&out.SessionId,
	)
	return out, err
}

func (d *faultDomain) one(rows *sql.Rows) (*Fault, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanFault(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *faultDomain) GetFault(ctx context.Context, seq int64) *lazy.Lazy[Fault] {
	l := lazy.New(ScanFault)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "seq", "at", "message", "session_id" FROM "faults" WHERE "seq" = $1`,
		seq,
	)
	out, err := ScanFault(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *faultDomain) GetFaultBatch(ctx context.Context, keys []int64) *lazy.Lazy[Fault] {
	l := lazy.New(ScanFault)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "seq", "at", "message", "session_id" FROM "faults" WHERE "seq" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Fault
	for rows.Next() {
		row, err := ScanFault(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *faultDomain) InsertFault(ctx context.Context, row Fault) (*Fault, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "faults" ("seq", "at", "message", "session_id") VALUES ($1, $2, $3, $4) RETURNING "seq", "at", "message", "session_id"`,
		row.Seq,
		row.At,
		row.Message,
		row.SessionId,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *faultDomain) DeleteFault(ctx context.Context, seq int64) (*Fault, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "faults" WHERE "seq" = $1 RETURNING "seq", "at", "message", "session_id"`,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *faultDomain) UpdateFault(ctx context.Context, row Fault) (*Fault, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "faults" SET "at" = $1, "message" = $2, "session_id" = $3 WHERE "seq" = $4 RETURNING "seq", "at", "message", "session_id"`,
		row.At,
		row.Message,
		row.SessionId,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
