// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type File struct {
	SessionId string `db:"session_id"`
	Path      string `db:"path"`
	Hash      string `db:"hash"`
	Mtime     int64  `db:"mtime"`
}

type FileDomain interface {
	GetFile(ctx context.Context, sessionId string, path string) *lazy.Lazy[File]
	WindowFileBySessionId(ctx context.Context, sessionId string, from string, to string, limit int32) *lazy.Lazy[File]
	PageFileBySessionId(ctx context.Context, sessionId string, after string, limit int32) *lazy.Lazy[File]
	InsertFile(ctx context.Context, row File) (*File, error)
	DeleteFile(ctx context.Context, sessionId string, path string) (*File, error)
	UpdateFile(ctx context.Context, row File) (*File, error)
}

type fileDomain struct{}

func NewFileDomain() *fileDomain {
	return &fileDomain{}
}

func ScanFile(row lazy.ScanRow) (File, error) {
	var out File
	err := row.Scan(
		&out.SessionId,
		&out.Path,
		&out.Hash,
		&out.Mtime,
	)
	return out, err
}

func (d *fileDomain) one(rows *sql.Rows) (*File, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanFile(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *fileDomain) GetFile(ctx context.Context, sessionId string, path string) *lazy.Lazy[File] {
	l := lazy.New(ScanFile)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "session_id", "path", "hash", "mtime" FROM "files" WHERE "session_id" = $1 AND "path" = $2`,
		sessionId,
		path,
	)
	out, err := ScanFile(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *fileDomain) WindowFileBySessionId(ctx context.Context, sessionId string, from string, to string, limit int32) *lazy.Lazy[File] {
	l := lazy.New(ScanFile)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "session_id", "path", "hash", "mtime" FROM "files" WHERE "session_id" = $1 AND "path" >= $2 AND "path" < $3 ORDER BY "session_id", "path" LIMIT $4`,
		sessionId,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []File
	for rows.Next() {
		row, err := ScanFile(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *fileDomain) PageFileBySessionId(ctx context.Context, sessionId string, after string, limit int32) *lazy.Lazy[File] {
	l := lazy.New(ScanFile)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "session_id", "path", "hash", "mtime" FROM "files" WHERE "session_id" = $1 AND "path" > $2 ORDER BY "session_id", "path" LIMIT $3`,
		sessionId,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []File
	for rows.Next() {
		row, err := ScanFile(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *fileDomain) InsertFile(ctx context.Context, row File) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "files" ("session_id", "path", "hash", "mtime") VALUES ($1, $2, $3, $4) RETURNING "session_id", "path", "hash", "mtime"`,
		row.SessionId,
		row.Path,
		row.Hash,
		row.Mtime,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *fileDomain) DeleteFile(ctx context.Context, sessionId string, path string) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "files" WHERE "session_id" = $1 AND "path" = $2 RETURNING "session_id", "path", "hash", "mtime"`,
		sessionId,
		path,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *fileDomain) UpdateFile(ctx context.Context, row File) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "files" SET "hash" = $1, "mtime" = $2 WHERE "session_id" = $3 AND "path" = $4 RETURNING "session_id", "path", "hash", "mtime"`,
		row.Hash,
		row.Mtime,
		row.SessionId,
		row.Path,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
