// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"
	"time"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Message struct {
	Seq       int64     `db:"seq"`
	Content   string    `db:"content"`
	CreatedAt time.Time `db:"created_at"`
	Reasoning *string   `db:"reasoning"`
	Role      string    `db:"role"`
	SessionId string    `db:"session_id"`
	ToolId    *string   `db:"tool_id"`
}

type MessageDomain interface {
	GetMessage(ctx context.Context, seq int64) *lazy.Lazy[Message]
	GetMessageBatch(ctx context.Context, keys []int64) *lazy.Lazy[Message]
	InsertMessage(ctx context.Context, row Message) (*Message, error)
	DeleteMessage(ctx context.Context, seq int64) (*Message, error)
	UpdateMessage(ctx context.Context, row Message) (*Message, error)
}

type messageDomain struct{}

func NewMessageDomain() *messageDomain {
	return &messageDomain{}
}

func ScanMessage(row lazy.ScanRow) (Message, error) {
	var out Message
	err := row.Scan(
		&out.Seq,
		&out.Content,
		&out.CreatedAt,
		&out.Reasoning,
		&out.Role,
		&out.SessionId,
		&out.ToolId,
	)
	return out, err
}

func (d *messageDomain) one(rows *sql.Rows) (*Message, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanMessage(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *messageDomain) GetMessage(ctx context.Context, seq int64) *lazy.Lazy[Message] {
	l := lazy.New(ScanMessage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id" FROM "messages" WHERE "seq" = $1`,
		seq,
	)
	out, err := ScanMessage(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *messageDomain) GetMessageBatch(ctx context.Context, keys []int64) *lazy.Lazy[Message] {
	l := lazy.New(ScanMessage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id" FROM "messages" WHERE "seq" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		row, err := ScanMessage(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *messageDomain) InsertMessage(ctx context.Context, row Message) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "messages" ("seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id"`,
		row.Seq,
		row.Content,
		row.CreatedAt,
		row.Reasoning,
		row.Role,
		row.SessionId,
		row.ToolId,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *messageDomain) DeleteMessage(ctx context.Context, seq int64) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "messages" WHERE "seq" = $1 RETURNING "seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id"`,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *messageDomain) UpdateMessage(ctx context.Context, row Message) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "messages" SET "content" = $1, "created_at" = $2, "reasoning" = $3, "role" = $4, "session_id" = $5, "tool_id" = $6 WHERE "seq" = $7 RETURNING "seq", "content", "created_at", "reasoning", "role", "session_id", "tool_id"`,
		row.Content,
		row.CreatedAt,
		row.Reasoning,
		row.Role,
		row.SessionId,
		row.ToolId,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
