// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"
	"time"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Session struct {
	Id        string     `db:"id"`
	Cwd       string     `db:"cwd"`
	EndedAt   *time.Time `db:"ended_at"`
	Exit      string     `db:"exit"`
	Model     string     `db:"model"`
	StartedAt time.Time  `db:"started_at"`
	Version   string     `db:"version"`
}

type SessionDomain interface {
	GetSession(ctx context.Context, id string) *lazy.Lazy[Session]
	GetSessionBatch(ctx context.Context, keys []string) *lazy.Lazy[Session]
	InsertSession(ctx context.Context, row Session) (*Session, error)
	DeleteSession(ctx context.Context, id string) (*Session, error)
	UpdateSession(ctx context.Context, row Session) (*Session, error)
}

type sessionDomain struct{}

func NewSessionDomain() *sessionDomain {
	return &sessionDomain{}
}

func ScanSession(row lazy.ScanRow) (Session, error) {
	var out Session
	err := row.Scan(
		&out.Id,
		&out.Cwd,
		&out.EndedAt,
		&out.Exit,
		&out.Model,
		&out.StartedAt,
		&out.Version,
	)
	return out, err
}

func (d *sessionDomain) one(rows *sql.Rows) (*Session, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanSession(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *sessionDomain) GetSession(ctx context.Context, id string) *lazy.Lazy[Session] {
	l := lazy.New(ScanSession)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "cwd", "ended_at", "exit", "model", "started_at", "version" FROM "sessions" WHERE "id" = $1`,
		id,
	)
	out, err := ScanSession(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *sessionDomain) GetSessionBatch(ctx context.Context, keys []string) *lazy.Lazy[Session] {
	l := lazy.New(ScanSession)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "cwd", "ended_at", "exit", "model", "started_at", "version" FROM "sessions" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Session
	for rows.Next() {
		row, err := ScanSession(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *sessionDomain) InsertSession(ctx context.Context, row Session) (*Session, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "sessions" ("id", "cwd", "ended_at", "exit", "model", "started_at", "version") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id", "cwd", "ended_at", "exit", "model", "started_at", "version"`,
		row.Id,
		row.Cwd,
		row.EndedAt,
		row.Exit,
		row.Model,
		row.StartedAt,
		row.Version,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *sessionDomain) DeleteSession(ctx context.Context, id string) (*Session, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "sessions" WHERE "id" = $1 RETURNING "id", "cwd", "ended_at", "exit", "model", "started_at", "version"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *sessionDomain) UpdateSession(ctx context.Context, row Session) (*Session, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "sessions" SET "cwd" = $1, "ended_at" = $2, "exit" = $3, "model" = $4, "started_at" = $5, "version" = $6 WHERE "id" = $7 RETURNING "id", "cwd", "ended_at", "exit", "model", "started_at", "version"`,
		row.Cwd,
		row.EndedAt,
		row.Exit,
		row.Model,
		row.StartedAt,
		row.Version,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
