// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type ToolCall struct {
	Id         string     `db:"id"`
	Args       string     `db:"args"`
	EndedAt    *time.Time `db:"ended_at"`
	Err        *string    `db:"err"`
	MessageSeq int64      `db:"message_seq"`
	Name       string     `db:"name"`
	Result     *string    `db:"result"`
	StartedAt  time.Time  `db:"started_at"`
}

type ToolCallDomain interface {
	GetToolCall(ctx context.Context, id string) *lazy.Lazy[ToolCall]
	GetToolCallBatch(ctx context.Context, keys []string) *lazy.Lazy[ToolCall]
	InsertToolCall(ctx context.Context, row ToolCall) (*ToolCall, error)
	DeleteToolCall(ctx context.Context, id string) (*ToolCall, error)
	UpdateToolCall(ctx context.Context, row ToolCall) (*ToolCall, error)
}

type toolCallDomain struct{}

func NewToolCallDomain() *toolCallDomain {
	return &toolCallDomain{}
}

func ScanToolCall(row lazy.ScanRow) (ToolCall, error) {
	var out ToolCall
	err := row.Scan(
		&out.Id,
		&out.Args,
		&out.EndedAt,
		&out.Err,
		&out.MessageSeq,
		&out.Name,
		&out.Result,
		&out.StartedAt,
	)
	return out, err
}

func (d *toolCallDomain) one(rows *sql.Rows) (*ToolCall, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanToolCall(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *toolCallDomain) GetToolCall(ctx context.Context, id string) *lazy.Lazy[ToolCall] {
	l := lazy.New(ScanToolCall)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at" FROM "tool_calls" WHERE "id" = $1`,
		id,
	)
	out, err := ScanToolCall(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *toolCallDomain) GetToolCallBatch(ctx context.Context, keys []string) *lazy.Lazy[ToolCall] {
	l := lazy.New(ScanToolCall)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at" FROM "tool_calls" WHERE "id" = ANY($1)`, keys)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []ToolCall
	for rows.Next() {
		row, err := ScanToolCall(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *toolCallDomain) InsertToolCall(ctx context.Context, row ToolCall) (*ToolCall, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "tool_calls" ("id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at"`,
		row.Id,
		row.Args,
		row.EndedAt,
		row.Err,
		row.MessageSeq,
		row.Name,
		row.Result,
		row.StartedAt,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *toolCallDomain) DeleteToolCall(ctx context.Context, id string) (*ToolCall, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "tool_calls" WHERE "id" = $1 RETURNING "id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *toolCallDomain) UpdateToolCall(ctx context.Context, row ToolCall) (*ToolCall, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "tool_calls" SET "args" = $1, "ended_at" = $2, "err" = $3, "message_seq" = $4, "name" = $5, "result" = $6, "started_at" = $7 WHERE "id" = $8 RETURNING "id", "args", "ended_at", "err", "message_seq", "name", "result", "started_at"`,
		row.Args,
		row.EndedAt,
		row.Err,
		row.MessageSeq,
		row.Name,
		row.Result,
		row.StartedAt,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
