// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Usage struct {
	MessageSeq int64 `db:"message_seq"`
	CacheRead  int64 `db:"cache_read"`
	CacheWrite int64 `db:"cache_write"`
	Completion int64 `db:"completion"`
	Prompt     int64 `db:"prompt"`
}

type UsageDomain interface {
	GetUsage(ctx context.Context, messageSeq int64) *lazy.Lazy[Usage]
	GetUsageBatch(ctx context.Context, keys []int64) *lazy.Lazy[Usage]
	InsertUsage(ctx context.Context, row Usage) (*Usage, error)
	DeleteUsage(ctx context.Context, messageSeq int64) (*Usage, error)
	UpdateUsage(ctx context.Context, row Usage) (*Usage, error)
}

type usageDomain struct{}

func NewUsageDomain() *usageDomain {
	return &usageDomain{}
}

func ScanUsage(row lazy.ScanRow) (Usage, error) {
	var out Usage
	err := row.Scan(
		&out.MessageSeq,
		&out.CacheRead,
		&out.CacheWrite,
		&out.Completion,
		&out.Prompt,
	)
	return out, err
}

func (d *usageDomain) one(rows *sql.Rows) (*Usage, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanUsage(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *usageDomain) GetUsage(ctx context.Context, messageSeq int64) *lazy.Lazy[Usage] {
	l := lazy.New(ScanUsage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "message_seq", "cache_read", "cache_write", "completion", "prompt" FROM "usage" WHERE "message_seq" = $1`,
		messageSeq,
	)
	out, err := ScanUsage(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *usageDomain) GetUsageBatch(ctx context.Context, keys []int64) *lazy.Lazy[Usage] {
	l := lazy.New(ScanUsage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "message_seq", "cache_read", "cache_write", "completion", "prompt" FROM "usage" WHERE "message_seq" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Usage
	for rows.Next() {
		row, err := ScanUsage(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *usageDomain) InsertUsage(ctx context.Context, row Usage) (*Usage, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "usage" ("message_seq", "cache_read", "cache_write", "completion", "prompt") VALUES ($1, $2, $3, $4, $5) RETURNING "message_seq", "cache_read", "cache_write", "completion", "prompt"`,
		row.MessageSeq,
		row.CacheRead,
		row.CacheWrite,
		row.Completion,
		row.Prompt,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *usageDomain) DeleteUsage(ctx context.Context, messageSeq int64) (*Usage, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "usage" WHERE "message_seq" = $1 RETURNING "message_seq", "cache_read", "cache_write", "completion", "prompt"`,
		messageSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *usageDomain) UpdateUsage(ctx context.Context, row Usage) (*Usage, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "usage" SET "cache_read" = $1, "cache_write" = $2, "completion" = $3, "prompt" = $4 WHERE "message_seq" = $5 RETURNING "message_seq", "cache_read", "cache_write", "completion", "prompt"`,
		row.CacheRead,
		row.CacheWrite,
		row.Completion,
		row.Prompt,
		row.MessageSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
