// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Memory struct {
	Id                 int64   `db:"id"`
	AccessCount        int64   `db:"access_count"`
	Content            string  `db:"content"`
	ContentMd5         string  `db:"content_md5"`
	CreatedAt          string  `db:"created_at"`
	Importance         float64 `db:"importance"`
	Kind               string  `db:"kind"`
	LastAccessedAt     *string `db:"last_accessed_at"`
	LastConsolidatedAt string  `db:"last_consolidated_at"`
	Scope              string  `db:"scope"`
	ScopeLabel         string  `db:"scope_label"`
	Source             *string `db:"source"`
	Strength           float64 `db:"strength"`
	SupersededBy       *int64  `db:"superseded_by"`
}

type MemoryDomain interface {
	GetMemory(ctx context.Context, id int64) *lazy.Lazy[Memory]
	GetMemoryBatch(ctx context.Context, keys []int64) *lazy.Lazy[Memory]
	ListMemoryById(ctx context.Context, id int64, limit int32) *lazy.Lazy[Memory]
	DeleteMemoryById(ctx context.Context, id int64) (int64, error)
	InsertMemory(ctx context.Context, row Memory) (*Memory, error)
	DeleteMemory(ctx context.Context, id int64) (*Memory, error)
	UpdateMemory(ctx context.Context, row Memory) (*Memory, error)
}

type memoryDomain struct{}

func NewMemoryDomain() *memoryDomain {
	return &memoryDomain{}
}

func ScanMemory(row lazy.ScanRow) (Memory, error) {
	var out Memory
	err := row.Scan(
		&out.Id,
		&out.AccessCount,
		&out.Content,
		&out.ContentMd5,
		&out.CreatedAt,
		&out.Importance,
		&out.Kind,
		&out.LastAccessedAt,
		&out.LastConsolidatedAt,
		&out.Scope,
		&out.ScopeLabel,
		&out.Source,
		&out.Strength,
		&out.SupersededBy,
	)
	return out, err
}

func (d *memoryDomain) one(rows *sql.Rows) (*Memory, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanMemory(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *memoryDomain) GetMemory(ctx context.Context, id int64) *lazy.Lazy[Memory] {
	l := lazy.New(ScanMemory)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by" FROM "memories" WHERE "id" = $1`,
		id,
	)
	out, err := ScanMemory(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *memoryDomain) GetMemoryBatch(ctx context.Context, keys []int64) *lazy.Lazy[Memory] {
	l := lazy.New(ScanMemory)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by" FROM "memories" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Memory
	for rows.Next() {
		row, err := ScanMemory(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *memoryDomain) ListMemoryById(ctx context.Context, id int64, limit int32) *lazy.Lazy[Memory] {
	l := lazy.New(ScanMemory)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by" FROM "memories" WHERE "id" = $1 LIMIT $2`,
		id, limit)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Memory
	for rows.Next() {
		row, err := ScanMemory(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *memoryDomain) DeleteMemoryById(ctx context.Context, id int64) (int64, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return 0, err
	}
	tag, err := tx.ExecContext(ctx, `DELETE FROM "memories" WHERE "id" = $1`,
		id)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected()
}

func (d *memoryDomain) InsertMemory(ctx context.Context, row Memory) (*Memory, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "memories" ("id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by"`,
		row.Id,
		row.AccessCount,
		row.Content,
		row.ContentMd5,
		row.CreatedAt,
		row.Importance,
		row.Kind,
		row.LastAccessedAt,
		row.LastConsolidatedAt,
		row.Scope,
		row.ScopeLabel,
		row.Source,
		row.Strength,
		row.SupersededBy,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *memoryDomain) DeleteMemory(ctx context.Context, id int64) (*Memory, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "memories" WHERE "id" = $1 RETURNING "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *memoryDomain) UpdateMemory(ctx context.Context, row Memory) (*Memory, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "memories" SET "access_count" = $1, "content" = $2, "content_md5" = $3, "created_at" = $4, "importance" = $5, "kind" = $6, "last_accessed_at" = $7, "last_consolidated_at" = $8, "scope" = $9, "scope_label" = $10, "source" = $11, "strength" = $12, "superseded_by" = $13 WHERE "id" = $14 RETURNING "id", "access_count", "content", "content_md5", "created_at", "importance", "kind", "last_accessed_at", "last_consolidated_at", "scope", "scope_label", "source", "strength", "superseded_by"`,
		row.AccessCount,
		row.Content,
		row.ContentMd5,
		row.CreatedAt,
		row.Importance,
		row.Kind,
		row.LastAccessedAt,
		row.LastConsolidatedAt,
		row.Scope,
		row.ScopeLabel,
		row.Source,
		row.Strength,
		row.SupersededBy,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
