// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Trigram struct {
	MemoryId int64  `db:"memory_id"`
	Gram     string `db:"gram"`
}

type TrigramDomain interface {
	GetTrigram(ctx context.Context, memoryId int64, gram string) *lazy.Lazy[Trigram]
	WindowTrigramByMemoryId(ctx context.Context, memoryId int64, from string, to string, limit int32) *lazy.Lazy[Trigram]
	PageTrigramByMemoryId(ctx context.Context, memoryId int64, after string, limit int32) *lazy.Lazy[Trigram]
	InsertTrigram(ctx context.Context, row Trigram) (*Trigram, error)
	DeleteTrigram(ctx context.Context, memoryId int64, gram string) (*Trigram, error)
}

type trigramDomain struct{}

func NewTrigramDomain() *trigramDomain {
	return &trigramDomain{}
}

func ScanTrigram(row lazy.ScanRow) (Trigram, error) {
	var out Trigram
	err := row.Scan(
		&out.MemoryId,
		&out.Gram,
	)
	return out, err
}

func (d *trigramDomain) one(rows *sql.Rows) (*Trigram, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTrigram(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *trigramDomain) GetTrigram(ctx context.Context, memoryId int64, gram string) *lazy.Lazy[Trigram] {
	l := lazy.New(ScanTrigram)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "memory_id", "gram" FROM "trigrams" WHERE "memory_id" = $1 AND "gram" = $2`,
		memoryId,
		gram,
	)
	out, err := ScanTrigram(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *trigramDomain) WindowTrigramByMemoryId(ctx context.Context, memoryId int64, from string, to string, limit int32) *lazy.Lazy[Trigram] {
	l := lazy.New(ScanTrigram)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "memory_id", "gram" FROM "trigrams" WHERE "memory_id" = $1 AND "gram" >= $2 AND "gram" < $3 ORDER BY "memory_id", "gram" LIMIT $4`,
		memoryId,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Trigram
	for rows.Next() {
		row, err := ScanTrigram(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *trigramDomain) PageTrigramByMemoryId(ctx context.Context, memoryId int64, after string, limit int32) *lazy.Lazy[Trigram] {
	l := lazy.New(ScanTrigram)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "memory_id", "gram" FROM "trigrams" WHERE "memory_id" = $1 AND "gram" > $2 ORDER BY "memory_id", "gram" LIMIT $3`,
		memoryId,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Trigram
	for rows.Next() {
		row, err := ScanTrigram(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *trigramDomain) InsertTrigram(ctx context.Context, row Trigram) (*Trigram, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "trigrams" ("memory_id", "gram") VALUES ($1, $2) RETURNING "memory_id", "gram"`,
		row.MemoryId,
		row.Gram,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *trigramDomain) DeleteTrigram(ctx context.Context, memoryId int64, gram string) (*Trigram, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "trigrams" WHERE "memory_id" = $1 AND "gram" = $2 RETURNING "memory_id", "gram"`,
		memoryId,
		gram,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
