// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "events" (
  "seq" INTEGER NOT NULL,
  "args" TEXT NOT NULL,
  "op" TEXT NOT NULL,
  "session" TEXT,
  "ts" TEXT NOT NULL,
  PRIMARY KEY ("seq")
)`,
		`CREATE TABLE IF NOT EXISTS "jobs" (
  "id" TEXT NOT NULL,
  "at" TEXT,
  "busy" TEXT NOT NULL,
  "created_seq" INTEGER NOT NULL,
  "cron" TEXT NOT NULL,
  "cwd" TEXT NOT NULL,
  "last_exit" INTEGER,
  "last_status" TEXT,
  "last_ts" TEXT,
  "model" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "prompt" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "updated_seq" INTEGER NOT NULL,
  PRIMARY KEY ("id")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "runs" (
  "seq" INTEGER NOT NULL,
  "duration_ms" INTEGER,
  "ended_at" TEXT NOT NULL,
  "exit" INTEGER,
  "job_id" TEXT NOT NULL,
  "log_path" TEXT,
  "reason" TEXT,
  "started_at" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  PRIMARY KEY ("seq")
)`,
	}
}
