// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type Edge struct {
	FromPackage string `db:"from_package"`
	FromName    string `db:"from_name"`
	ToPackage   string `db:"to_package"`
	ToName      string `db:"to_name"`
	File        string `db:"file"`
	Line        int64  `db:"line"`
}

type EdgeDomain interface {
	GetEdge(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, line int64) *lazy.Lazy[Edge]
	WindowEdgeByFromPackageFromNameToPackageToNameFile(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, from int64, to int64, limit int32) *lazy.Lazy[Edge]
	PageEdgeByFromPackageFromNameToPackageToNameFile(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, after int64, limit int32) *lazy.Lazy[Edge]
	InsertEdge(ctx context.Context, row Edge) (*Edge, error)
	DeleteEdge(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, line int64) (*Edge, error)
}

type edgeDomain struct{}

func NewEdgeDomain() *edgeDomain {
	return &edgeDomain{}
}

func ScanEdge(row lazy.ScanRow) (Edge, error) {
	var out Edge
	err := row.Scan(
		&out.FromPackage,
		&out.FromName,
		&out.ToPackage,
		&out.ToName,
		&out.File,
		&out.Line,
	)
	return out, err
}

func (d *edgeDomain) one(rows *sql.Rows) (*Edge, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanEdge(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *edgeDomain) GetEdge(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, line int64) *lazy.Lazy[Edge] {
	l := lazy.New(ScanEdge)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "from_package", "from_name", "to_package", "to_name", "file", "line" FROM "edges" WHERE "from_package" = $1 AND "from_name" = $2 AND "to_package" = $3 AND "to_name" = $4 AND "file" = $5 AND "line" = $6`,
		fromPackage,
		fromName,
		toPackage,
		toName,
		file,
		line,
	)
	out, err := ScanEdge(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *edgeDomain) WindowEdgeByFromPackageFromNameToPackageToNameFile(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, from int64, to int64, limit int32) *lazy.Lazy[Edge] {
	l := lazy.New(ScanEdge)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "from_package", "from_name", "to_package", "to_name", "file", "line" FROM "edges" WHERE "from_package" = $1 AND "from_name" = $2 AND "to_package" = $3 AND "to_name" = $4 AND "file" = $5 AND "line" >= $6 AND "line" < $7 ORDER BY "from_package", "from_name", "to_package", "to_name", "file", "line" LIMIT $8`,
		fromPackage,
		fromName,
		toPackage,
		toName,
		file,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Edge
	for rows.Next() {
		row, err := ScanEdge(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *edgeDomain) PageEdgeByFromPackageFromNameToPackageToNameFile(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, after int64, limit int32) *lazy.Lazy[Edge] {
	l := lazy.New(ScanEdge)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "from_package", "from_name", "to_package", "to_name", "file", "line" FROM "edges" WHERE "from_package" = $1 AND "from_name" = $2 AND "to_package" = $3 AND "to_name" = $4 AND "file" = $5 AND "line" > $6 ORDER BY "from_package", "from_name", "to_package", "to_name", "file", "line" LIMIT $7`,
		fromPackage,
		fromName,
		toPackage,
		toName,
		file,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Edge
	for rows.Next() {
		row, err := ScanEdge(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *edgeDomain) InsertEdge(ctx context.Context, row Edge) (*Edge, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "edges" ("from_package", "from_name", "to_package", "to_name", "file", "line") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "from_package", "from_name", "to_package", "to_name", "file", "line"`,
		row.FromPackage,
		row.FromName,
		row.ToPackage,
		row.ToName,
		row.File,
		row.Line,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *edgeDomain) DeleteEdge(ctx context.Context, fromPackage string, fromName string, toPackage string, toName string, file string, line int64) (*Edge, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "edges" WHERE "from_package" = $1 AND "from_name" = $2 AND "to_package" = $3 AND "to_name" = $4 AND "file" = $5 AND "line" = $6 RETURNING "from_package", "from_name", "to_package", "to_name", "file", "line"`,
		fromPackage,
		fromName,
		toPackage,
		toName,
		file,
		line,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
