// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type File struct {
	Path     string  `db:"path"`
	EdgesSha *string `db:"edges_sha"`
	Language string  `db:"language"`
	Sha256   string  `db:"sha256"`
}

type FileDomain interface {
	GetFile(ctx context.Context, path string) *lazy.Lazy[File]
	GetFileBatch(ctx context.Context, keys []string) *lazy.Lazy[File]
	InsertFile(ctx context.Context, row File) (*File, error)
	DeleteFile(ctx context.Context, path string) (*File, error)
	UpdateFile(ctx context.Context, row File) (*File, error)
}

type fileDomain struct{}

func NewFileDomain() *fileDomain {
	return &fileDomain{}
}

func ScanFile(row lazy.ScanRow) (File, error) {
	var out File
	err := row.Scan(
		&out.Path,
		&out.EdgesSha,
		&out.Language,
		&out.Sha256,
	)
	return out, err
}

func (d *fileDomain) one(rows *sql.Rows) (*File, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanFile(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *fileDomain) GetFile(ctx context.Context, path string) *lazy.Lazy[File] {
	l := lazy.New(ScanFile)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "path", "edges_sha", "language", "sha256" FROM "files" WHERE "path" = $1`,
		path,
	)
	out, err := ScanFile(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *fileDomain) GetFileBatch(ctx context.Context, keys []string) *lazy.Lazy[File] {
	l := lazy.New(ScanFile)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "path", "edges_sha", "language", "sha256" FROM "files" WHERE "path" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []File
	for rows.Next() {
		row, err := ScanFile(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *fileDomain) InsertFile(ctx context.Context, row File) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "files" ("path", "edges_sha", "language", "sha256") VALUES ($1, $2, $3, $4) RETURNING "path", "edges_sha", "language", "sha256"`,
		row.Path,
		row.EdgesSha,
		row.Language,
		row.Sha256,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *fileDomain) DeleteFile(ctx context.Context, path string) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "files" WHERE "path" = $1 RETURNING "path", "edges_sha", "language", "sha256"`,
		path,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *fileDomain) UpdateFile(ctx context.Context, row File) (*File, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "files" SET "edges_sha" = $1, "language" = $2, "sha256" = $3 WHERE "path" = $4 RETURNING "path", "edges_sha", "language", "sha256"`,
		row.EdgesSha,
		row.Language,
		row.Sha256,
		row.Path,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
