// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type Symbol struct {
	Package string `db:"package"`
	Name    string `db:"name"`
	File    string `db:"file"`
	Kind    string `db:"kind"`
	Line    int64  `db:"line"`
}

type SymbolDomain interface {
	GetSymbol(ctx context.Context, package_ string, name string) *lazy.Lazy[Symbol]
	WindowSymbolByPackage(ctx context.Context, package_ string, from string, to string, limit int32) *lazy.Lazy[Symbol]
	PageSymbolByPackage(ctx context.Context, package_ string, after string, limit int32) *lazy.Lazy[Symbol]
	InsertSymbol(ctx context.Context, row Symbol) (*Symbol, error)
	DeleteSymbol(ctx context.Context, package_ string, name string) (*Symbol, error)
	UpdateSymbol(ctx context.Context, row Symbol) (*Symbol, error)
}

type symbolDomain struct{}

func NewSymbolDomain() *symbolDomain {
	return &symbolDomain{}
}

func ScanSymbol(row lazy.ScanRow) (Symbol, error) {
	var out Symbol
	err := row.Scan(
		&out.Package,
		&out.Name,
		&out.File,
		&out.Kind,
		&out.Line,
	)
	return out, err
}

func (d *symbolDomain) one(rows *sql.Rows) (*Symbol, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanSymbol(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *symbolDomain) GetSymbol(ctx context.Context, package_ string, name string) *lazy.Lazy[Symbol] {
	l := lazy.New(ScanSymbol)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "package", "name", "file", "kind", "line" FROM "symbols" WHERE "package" = $1 AND "name" = $2`,
		package_,
		name,
	)
	out, err := ScanSymbol(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *symbolDomain) WindowSymbolByPackage(ctx context.Context, package_ string, from string, to string, limit int32) *lazy.Lazy[Symbol] {
	l := lazy.New(ScanSymbol)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "package", "name", "file", "kind", "line" FROM "symbols" WHERE "package" = $1 AND "name" >= $2 AND "name" < $3 ORDER BY "package", "name" LIMIT $4`,
		package_,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Symbol
	for rows.Next() {
		row, err := ScanSymbol(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *symbolDomain) PageSymbolByPackage(ctx context.Context, package_ string, after string, limit int32) *lazy.Lazy[Symbol] {
	l := lazy.New(ScanSymbol)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "package", "name", "file", "kind", "line" FROM "symbols" WHERE "package" = $1 AND "name" > $2 ORDER BY "package", "name" LIMIT $3`,
		package_,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Symbol
	for rows.Next() {
		row, err := ScanSymbol(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *symbolDomain) InsertSymbol(ctx context.Context, row Symbol) (*Symbol, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "symbols" ("package", "name", "file", "kind", "line") VALUES ($1, $2, $3, $4, $5) RETURNING "package", "name", "file", "kind", "line"`,
		row.Package,
		row.Name,
		row.File,
		row.Kind,
		row.Line,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *symbolDomain) DeleteSymbol(ctx context.Context, package_ string, name string) (*Symbol, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "symbols" WHERE "package" = $1 AND "name" = $2 RETURNING "package", "name", "file", "kind", "line"`,
		package_,
		name,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *symbolDomain) UpdateSymbol(ctx context.Context, row Symbol) (*Symbol, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "symbols" SET "file" = $1, "kind" = $2, "line" = $3 WHERE "package" = $4 AND "name" = $5 RETURNING "package", "name", "file", "kind", "line"`,
		row.File,
		row.Kind,
		row.Line,
		row.Package,
		row.Name,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
