// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type Decision struct {
	Id             int64    `db:"id"`
	Answer         string   `db:"answer"`
	Confidence     *float64 `db:"confidence"`
	Decider        string   `db:"decider"`
	Outcome        *string  `db:"outcome"`
	Question       string   `db:"question"`
	Reviewer       *string  `db:"reviewer"`
	ReviewerAnswer *string  `db:"reviewer_answer"`
	Scope          string   `db:"scope"`
	Session        *string  `db:"session"`
	Site           string   `db:"site"`
	State          string   `db:"state"`
	Status         string   `db:"status"`
	Ts             string   `db:"ts"`
	Unsure         bool     `db:"unsure"`
}

type DecisionDomain interface {
	GetDecision(ctx context.Context, id int64) *lazy.Lazy[Decision]
	GetDecisionBatch(ctx context.Context, keys []int64) *lazy.Lazy[Decision]
	InsertDecision(ctx context.Context, row Decision) (*Decision, error)
	DeleteDecision(ctx context.Context, id int64) (*Decision, error)
	UpdateDecision(ctx context.Context, row Decision) (*Decision, error)
}

type decisionDomain struct{}

func NewDecisionDomain() *decisionDomain {
	return &decisionDomain{}
}

func ScanDecision(row lazy.ScanRow) (Decision, error) {
	var out Decision
	err := row.Scan(
		&out.Id,
		&out.Answer,
		&out.Confidence,
		&out.Decider,
		&out.Outcome,
		&out.Question,
		&out.Reviewer,
		&out.ReviewerAnswer,
		&out.Scope,
		&out.Session,
		&out.Site,
		&out.State,
		&out.Status,
		&out.Ts,
		&out.Unsure,
	)
	return out, err
}

func (d *decisionDomain) one(rows *sql.Rows) (*Decision, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanDecision(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *decisionDomain) GetDecision(ctx context.Context, id int64) *lazy.Lazy[Decision] {
	l := lazy.New(ScanDecision)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure" FROM "decisions" WHERE "id" = $1`,
		id,
	)
	out, err := ScanDecision(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *decisionDomain) GetDecisionBatch(ctx context.Context, keys []int64) *lazy.Lazy[Decision] {
	l := lazy.New(ScanDecision)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure" FROM "decisions" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Decision
	for rows.Next() {
		row, err := ScanDecision(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *decisionDomain) InsertDecision(ctx context.Context, row Decision) (*Decision, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "decisions" ("id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure"`,
		row.Id,
		row.Answer,
		row.Confidence,
		row.Decider,
		row.Outcome,
		row.Question,
		row.Reviewer,
		row.ReviewerAnswer,
		row.Scope,
		row.Session,
		row.Site,
		row.State,
		row.Status,
		row.Ts,
		row.Unsure,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *decisionDomain) DeleteDecision(ctx context.Context, id int64) (*Decision, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "decisions" WHERE "id" = $1 RETURNING "id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *decisionDomain) UpdateDecision(ctx context.Context, row Decision) (*Decision, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "decisions" SET "answer" = $1, "confidence" = $2, "decider" = $3, "outcome" = $4, "question" = $5, "reviewer" = $6, "reviewer_answer" = $7, "scope" = $8, "session" = $9, "site" = $10, "state" = $11, "status" = $12, "ts" = $13, "unsure" = $14 WHERE "id" = $15 RETURNING "id", "answer", "confidence", "decider", "outcome", "question", "reviewer", "reviewer_answer", "scope", "session", "site", "state", "status", "ts", "unsure"`,
		row.Answer,
		row.Confidence,
		row.Decider,
		row.Outcome,
		row.Question,
		row.Reviewer,
		row.ReviewerAnswer,
		row.Scope,
		row.Session,
		row.Site,
		row.State,
		row.Status,
		row.Ts,
		row.Unsure,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
