// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type Training struct {
	Id         int64   `db:"id"`
	Candidate  string  `db:"candidate"`
	Checkpoint string  `db:"checkpoint"`
	Constant   string  `db:"constant"`
	HeldRows   int64   `db:"held_rows"`
	Incumbent  *string `db:"incumbent"`
	Promoted   bool    `db:"promoted"`
	Rows       int64   `db:"rows"`
	RunDir     string  `db:"run_dir"`
	Scope      string  `db:"scope"`
	Skipped    int64   `db:"skipped"`
	TrainRows  int64   `db:"train_rows"`
	Trainer    string  `db:"trainer"`
	Ts         string  `db:"ts"`
}

type TrainingDomain interface {
	GetTraining(ctx context.Context, id int64) *lazy.Lazy[Training]
	GetTrainingBatch(ctx context.Context, keys []int64) *lazy.Lazy[Training]
	InsertTraining(ctx context.Context, row Training) (*Training, error)
	DeleteTraining(ctx context.Context, id int64) (*Training, error)
	UpdateTraining(ctx context.Context, row Training) (*Training, error)
}

type trainingDomain struct{}

func NewTrainingDomain() *trainingDomain {
	return &trainingDomain{}
}

func ScanTraining(row lazy.ScanRow) (Training, error) {
	var out Training
	err := row.Scan(
		&out.Id,
		&out.Candidate,
		&out.Checkpoint,
		&out.Constant,
		&out.HeldRows,
		&out.Incumbent,
		&out.Promoted,
		&out.Rows,
		&out.RunDir,
		&out.Scope,
		&out.Skipped,
		&out.TrainRows,
		&out.Trainer,
		&out.Ts,
	)
	return out, err
}

func (d *trainingDomain) one(rows *sql.Rows) (*Training, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTraining(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *trainingDomain) GetTraining(ctx context.Context, id int64) *lazy.Lazy[Training] {
	l := lazy.New(ScanTraining)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts" FROM "trainings" WHERE "id" = $1`,
		id,
	)
	out, err := ScanTraining(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *trainingDomain) GetTrainingBatch(ctx context.Context, keys []int64) *lazy.Lazy[Training] {
	l := lazy.New(ScanTraining)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts" FROM "trainings" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Training
	for rows.Next() {
		row, err := ScanTraining(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *trainingDomain) InsertTraining(ctx context.Context, row Training) (*Training, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "trainings" ("id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts"`,
		row.Id,
		row.Candidate,
		row.Checkpoint,
		row.Constant,
		row.HeldRows,
		row.Incumbent,
		row.Promoted,
		row.Rows,
		row.RunDir,
		row.Scope,
		row.Skipped,
		row.TrainRows,
		row.Trainer,
		row.Ts,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *trainingDomain) DeleteTraining(ctx context.Context, id int64) (*Training, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "trainings" WHERE "id" = $1 RETURNING "id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *trainingDomain) UpdateTraining(ctx context.Context, row Training) (*Training, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "trainings" SET "candidate" = $1, "checkpoint" = $2, "constant" = $3, "held_rows" = $4, "incumbent" = $5, "promoted" = $6, "rows" = $7, "run_dir" = $8, "scope" = $9, "skipped" = $10, "train_rows" = $11, "trainer" = $12, "ts" = $13 WHERE "id" = $14 RETURNING "id", "candidate", "checkpoint", "constant", "held_rows", "incumbent", "promoted", "rows", "run_dir", "scope", "skipped", "train_rows", "trainer", "ts"`,
		row.Candidate,
		row.Checkpoint,
		row.Constant,
		row.HeldRows,
		row.Incumbent,
		row.Promoted,
		row.Rows,
		row.RunDir,
		row.Scope,
		row.Skipped,
		row.TrainRows,
		row.Trainer,
		row.Ts,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
