// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Job struct {
	Id         string  `db:"id"`
	At         *string `db:"at"`
	Busy       string  `db:"busy"`
	CreatedSeq int64   `db:"created_seq"`
	Cron       string  `db:"cron"`
	Cwd        string  `db:"cwd"`
	LastExit   *int64  `db:"last_exit"`
	LastStatus *string `db:"last_status"`
	LastTs     *string `db:"last_ts"`
	Model      string  `db:"model"`
	Name       string  `db:"name"`
	Prompt     string  `db:"prompt"`
	State      string  `db:"state"`
	UpdatedSeq int64   `db:"updated_seq"`
}

type JobDomain interface {
	GetJob(ctx context.Context, id string) *lazy.Lazy[Job]
	GetJobBatch(ctx context.Context, keys []string) *lazy.Lazy[Job]
	InsertJob(ctx context.Context, row Job) (*Job, error)
	DeleteJob(ctx context.Context, id string) (*Job, error)
	UpdateJob(ctx context.Context, row Job) (*Job, error)
}

type jobDomain struct{}

func NewJobDomain() *jobDomain {
	return &jobDomain{}
}

func ScanJob(row lazy.ScanRow) (Job, error) {
	var out Job
	err := row.Scan(
		&out.Id,
		&out.At,
		&out.Busy,
		&out.CreatedSeq,
		&out.Cron,
		&out.Cwd,
		&out.LastExit,
		&out.LastStatus,
		&out.LastTs,
		&out.Model,
		&out.Name,
		&out.Prompt,
		&out.State,
		&out.UpdatedSeq,
	)
	return out, err
}

func (d *jobDomain) one(rows *sql.Rows) (*Job, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanJob(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *jobDomain) GetJob(ctx context.Context, id string) *lazy.Lazy[Job] {
	l := lazy.New(ScanJob)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq" FROM "jobs" WHERE "id" = $1`,
		id,
	)
	out, err := ScanJob(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *jobDomain) GetJobBatch(ctx context.Context, keys []string) *lazy.Lazy[Job] {
	l := lazy.New(ScanJob)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq" FROM "jobs" WHERE "id" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Job
	for rows.Next() {
		row, err := ScanJob(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *jobDomain) InsertJob(ctx context.Context, row Job) (*Job, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "jobs" ("id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq"`,
		row.Id,
		row.At,
		row.Busy,
		row.CreatedSeq,
		row.Cron,
		row.Cwd,
		row.LastExit,
		row.LastStatus,
		row.LastTs,
		row.Model,
		row.Name,
		row.Prompt,
		row.State,
		row.UpdatedSeq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *jobDomain) DeleteJob(ctx context.Context, id string) (*Job, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "jobs" WHERE "id" = $1 RETURNING "id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq"`,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *jobDomain) UpdateJob(ctx context.Context, row Job) (*Job, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "jobs" SET "at" = $1, "busy" = $2, "created_seq" = $3, "cron" = $4, "cwd" = $5, "last_exit" = $6, "last_status" = $7, "last_ts" = $8, "model" = $9, "name" = $10, "prompt" = $11, "state" = $12, "updated_seq" = $13 WHERE "id" = $14 RETURNING "id", "at", "busy", "created_seq", "cron", "cwd", "last_exit", "last_status", "last_ts", "model", "name", "prompt", "state", "updated_seq"`,
		row.At,
		row.Busy,
		row.CreatedSeq,
		row.Cron,
		row.Cwd,
		row.LastExit,
		row.LastStatus,
		row.LastTs,
		row.Model,
		row.Name,
		row.Prompt,
		row.State,
		row.UpdatedSeq,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
