// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/looper/store/lazy"
	"github.com/mrsirg97-rgb/looper/store/sqlx"
)

type Run struct {
	Seq        int64   `db:"seq"`
	DurationMs *int64  `db:"duration_ms"`
	EndedAt    string  `db:"ended_at"`
	Exit       *int64  `db:"exit"`
	JobId      string  `db:"job_id"`
	LogPath    *string `db:"log_path"`
	Reason     *string `db:"reason"`
	StartedAt  string  `db:"started_at"`
	Status     string  `db:"status"`
}

type RunDomain interface {
	GetRun(ctx context.Context, seq int64) *lazy.Lazy[Run]
	GetRunBatch(ctx context.Context, keys []int64) *lazy.Lazy[Run]
	InsertRun(ctx context.Context, row Run) (*Run, error)
	DeleteRun(ctx context.Context, seq int64) (*Run, error)
	UpdateRun(ctx context.Context, row Run) (*Run, error)
}

type runDomain struct{}

func NewRunDomain() *runDomain {
	return &runDomain{}
}

func ScanRun(row lazy.ScanRow) (Run, error) {
	var out Run
	err := row.Scan(
		&out.Seq,
		&out.DurationMs,
		&out.EndedAt,
		&out.Exit,
		&out.JobId,
		&out.LogPath,
		&out.Reason,
		&out.StartedAt,
		&out.Status,
	)
	return out, err
}

func (d *runDomain) one(rows *sql.Rows) (*Run, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanRun(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *runDomain) GetRun(ctx context.Context, seq int64) *lazy.Lazy[Run] {
	l := lazy.New(ScanRun)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status" FROM "runs" WHERE "seq" = $1`,
		seq,
	)
	out, err := ScanRun(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *runDomain) GetRunBatch(ctx context.Context, keys []int64) *lazy.Lazy[Run] {
	l := lazy.New(ScanRun)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status" FROM "runs" WHERE "seq" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Run
	for rows.Next() {
		row, err := ScanRun(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *runDomain) InsertRun(ctx context.Context, row Run) (*Run, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "runs" ("seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status"`,
		row.Seq,
		row.DurationMs,
		row.EndedAt,
		row.Exit,
		row.JobId,
		row.LogPath,
		row.Reason,
		row.StartedAt,
		row.Status,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *runDomain) DeleteRun(ctx context.Context, seq int64) (*Run, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "runs" WHERE "seq" = $1 RETURNING "seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status"`,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *runDomain) UpdateRun(ctx context.Context, row Run) (*Run, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "runs" SET "duration_ms" = $1, "ended_at" = $2, "exit" = $3, "job_id" = $4, "log_path" = $5, "reason" = $6, "started_at" = $7, "status" = $8 WHERE "seq" = $9 RETURNING "seq", "duration_ms", "ended_at", "exit", "job_id", "log_path", "reason", "started_at", "status"`,
		row.DurationMs,
		row.EndedAt,
		row.Exit,
		row.JobId,
		row.LogPath,
		row.Reason,
		row.StartedAt,
		row.Status,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
