// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "edges" (
  "from_package" TEXT NOT NULL,
  "from_name" TEXT NOT NULL,
  "to_package" TEXT NOT NULL,
  "to_name" TEXT NOT NULL,
  "file" TEXT NOT NULL,
  "line" INTEGER NOT NULL,
  PRIMARY KEY ("from_package", "from_name", "to_package", "to_name", "file", "line")
)`,
		`CREATE TABLE IF NOT EXISTS "files" (
  "path" TEXT NOT NULL,
  "edges_sha" TEXT,
  "language" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  PRIMARY KEY ("path")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "symbols" (
  "package" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "end_line" INTEGER NOT NULL,
  "file" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "line" INTEGER NOT NULL,
  PRIMARY KEY ("package", "name")
)`,
	}
}
